title: TJ Latin
description: >- 
  Welcome to TJ Latin! We're TJ's best community, full of passionate students that can't wait to share the world of Classics with others.
baseurl: "/latin"

show_excerpts: true

plugins:
  - jekyll-feed

collections:
  officers:
    order:
      - jing-liu.md
      - jw-strassberg.md
      - nicole-koko.md
      - abi-sastry.md
      - kelly-mao.md
      - emerson-rodriguez.md
      - michelle-ru.md
      - jennifer-hunsinger.md
      - william-mclaughlin.md
      - thomas-donohue.md
      - ryan-dwyer.md
      - owen-grannis.md
      - andrew-hadikusumo.md
      - rhea-goswami.md
      - reva-hirave.md
      - nilima-khanna.md
      - anna-hsu.md
      - nidhish-lella.md
      - karen-song.md
      - miranda-xiong.md
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "officers"
    values:
      layout: "officer"
      nav: "/about.html"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      nav: "/news.html"
  - scope:
      path: "archives"
      type: "pages"
    values:
      layout: "archive"
      nav: "/archives.html"
  - scope:
      path: ""
    values:
      layout: "default"