title: TJ Latin
description: >-
  Welcome to TJ Latin! We're TJ's best community, full of passionate students that can't wait to share the world of Classics with others.
baseurl: "/latin"

show_excerpts: true

plugins:
  - jekyll-feed

collections:
  officers:
    order:
      - clarissa-ding.md
      - lauren-fisher.md
      - nivika-gandhi.md
      - laura-guo.md
      - alex-yung.md
      - rex-allard.md
      - nina-garces.md
      - cierra-min.md
      - avery-park.md
      - ellie-chen.md
      - gabriel-ascoli.md
      - amit-erraguntla.md
      - lucy-watts.md
      - melissa-brown.md
      - saranya-gadwala.md
      - vivian-xue.md
      - derek-li.md
      - daphne-feigin.md
      - patrick-gaucher.md
      - prithvi-seri.md
      - tarini-basireddy.md
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "officers"
    values:
      layout: "officer"
      nav: "/about.html"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      nav: "/news.html"
  - scope:
      path: "archives"
      type: "pages"
    values:
      layout: "archive"
      nav: "/archives.html"
  - scope:
      path: ""
    values:
      layout: "default"
