title: TJ Latin
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/latin" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true

# Build settings
plugins:
  - jekyll-feed

collections:
  officers:
    order:
      - jing-liu.md
      - jw-strassberg.md
      - nicole-koko.md
      - abi-sastry.md
      - kelly-mao.md
      - emerson-rodriguez.md
      - michelle-ru.md
      - jennifer-hunsinger.md
      - william-mclaughlin.md
      - thomas-donohue.md
      - ryan-dwyer.md
      - owen-grannis.md
      - andrew-hadikusumo.md
      - rhea-goswami.md
      - reva-hirave.md
      - nilima-khanna.md
      - anna-hsu.md
      - nidhish-lella.md
      - karen-song.md
      - miranda-xiong.md
    output: true

defaults:
  - scope:
      path: ""
      type: "officers"
    values:
      layout: "officer"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
