title: TJ Latin
description: >-
  Welcome to TJ Latin! We're TJ's best community, full of passionate students that can't wait to share the world of Classics with others.
baseurl: "/latin"

show_excerpts: true

plugins:
  - jekyll-feed

collections:
  officers:
    order:
      - michelle-ru.md
      - abi-sastry.md
      - clarissa-ding.md
      - lauren-fisher.md
      - patrick-gaucher.md
      - alex-yung.md
      - prithvi-seri.md
      - shruti-shah.md
      - daphne-feigin.md
      - rae-trainer.md
      - ryan-dwyer.md
      - anand-advani.md
      - gabriel-ascoli.md
      - rhea-goswami.md
      - alison-song.md
      - tarini-basireddy.md
      - anna-hsu.md
      - derek-li.md
      - jennifer-hunsinger.md
      - william-mclaughlin.md
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "officers"
    values:
      layout: "officer"
      nav: "/about.html"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      nav: "/news.html"
  - scope:
      path: "archives"
      type: "pages"
    values:
      layout: "archive"
      nav: "/archives.html"
  - scope:
      path: ""
    values:
      layout: "default"
